language: node_js
node_js: "8"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn test --coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
before_deploy:
  - yarn global add netlify-cli
  - yarn build
  # - yarn build-storybook # uncomment when we actually start using storybook
deploy:
  provider: script
  skip-cleanup: true
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  # && netlify deploy -s $NETLIFY_SITE_ID_SB -t $NETLIFY_ACCESS_TOKEN -p ./storybook-static
  on:
    branch: master
