version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    branches:
      ignore:
        - gh-pages

    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages

    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            yarn test --coverage
            ./cc-test-reporter after-build --exit-code $?
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME

            git clone $CIRCLE_REPOSITORY_URL out

            cd out
            git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
            git rm -rf .
            cd ..

            yarn build

            cp -a build/. out/.
            cd out

            git add -A
            git commit -m "Automated deployment from CircleCI (${CIRCLE_SHA1})" --allow-empty

            git push origin $TARGET_BRANCH
